name: OnePlusOneEA
type: MuPlusLamdaEA
use_dynamic_pop_size: false
# mutation rate arguments
static_indpb: 0.01
use_dynamic_mutation: true
indpb_fn:
  _target_: run_helpers.inverse_n_mut_rate
  n_items: ${problem.dimensions}
  noise: null
# algorithm arguments for initialisation
init_args:
  _target_: Algorithms.MuPlusLamdaEA
  mu: 1
  lam: 1
  mutate_function: "probFlipBit"
  mutate_params:
    indpb: null